quarkus:
  http:
    port: 8081
  rest-client:
    user-data-api:
      url: ${USER_DATA_API_URL:http://localhost:8080}
      disable-default-mapper: true
  oidc-client:
    auth-server-url: http://34.142.154.181/realms/david-test-realm
    user-data-api:
      client-id: keycloak-client-svc-poc-client
      auth-server-url: http://34.142.154.181/realms/david-test-realm
      credentials:
        secret: 443ayFouSSvXkvavB6bZHkyh38Fw9D5p
      grant:
        type: client
  log:
    category:
      # Enable detailed OIDC logging
      "io.quarkus.oidc":
        level: DEBUG
      "io.quarkus.oidc.runtime":
        level: TRACE

      # Show HTTP client requests to Keycloak
      "io.vertx.ext.web.client":
        level: DEBUG

      # Show token validation details
      "io.quarkus.oidc.runtime.OidcProvider":
        level: DEBUG
